# Use root/example as user/password credentials
version: '3'

services:
    mysql_db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: facturacion
            MYSQL_ROOT_PASSWORD: example
            MYSQL_USER: root
            MYSQL_PASSWORD: example
        ports:
            - 5500:3306
        volumes:
            - /data/mysql
        networks:
            - springmysql-net
    adminer:
        image: adminer
        restart: unless-stopped
        ports:
            - 8081:8081
        networks:
            - springmysql-net

    facturacion-app:
        build: .
        ports:
            - 8080:8080
        environment:
            - spring.datasource.url=jdbc:mysql://mysql_db:3306/facturacion?useSSL=false
            - spring.datasource.username=root
            - spring.datasource.password=example
            - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
            - spring.jpa.defer-datasource-initialization=true
            - spring.sql.init.mode=always
            - spring.jpa.show-sql=true
        networks:
            - springmysql-net

networks:
    springmysql-net:


# build: docker-compose -f stack.yml build
# run: docker-compose -f stack.yml up
# stop: docker-compose down --rmi all